package P_20211222.exception;

import java.util.Scanner;

public class Exception05P348 {
	public static void main(String[] args) {
		//예외발생 케이스 4
		int[] arr1 = new int[5];
		
		System.out.println(arr1[11]);
	}
}
